enum WalletConnectorEventType {
  WALLET_CONNECT,
  WALLET_DISCONNECT,

  // Wallet Events
  WALLET_LOCKED,
  WALLET_AUTO_CONNECTED,
  WALLET_CHANGE,

  // Change events
  WALLET_CHANGE_ADDRESS,
  WALLET_CHANGE_CHAIN,

  // Error events
  ERROR_WRONG_NETWORK,
  ERROR_AUTO_CONNECT_EXPIRED,

  ERROR_NO_MATCHING_CONNECTOR,
  ERROR_UNLOCK_REQUIRED,

  ERROR_INVALID_WALLET_CONNECTOR,
}

export { WalletConnectorEventType };
